### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by balu-ertl** [brainsum/drupal-dev-tools#1]
After reading about Composer's [plugin system](https://getcomposer.org/doc/articles/plugins.md#using-plugins), first I added these two package resources to the `composer.json` file in my `COMPOSER_HOME` directory ([as read here](https://getcomposer.org/doc/03-cli.md#composer-home)):
```"repositories": {
  "drupal": {
    "type": "composer",
    "url": "https://packages.drupal.org/8"
  },
  "brainsum/drupal-dev-tools": {
    "type": "vcs",
    "url": "https://github.com/brainsum/drupal-dev-tools"
  }
}
```

Then tried to install with this command:
`$ composer global require brainsum/drupal-dev-tools:'^0.2.0'`
Here I got the following result:
```
Problem 1
    - Installation request for brainsum/drupal-dev-tools ^0.2.0 -> satisfiable by brainsum/drupal-dev-tools[0.2.0].
    - brainsum/drupal-dev-tools 0.2.0 requires drupal-composer/drupal-security-advisories 8.x-dev -> satisfiable by drupal-composer/drupal-security-advisories[8.x-dev] but these conflict with your requirements or minimum-stability.
```
So I started to append all the nagged packages to the end of the command, like this:
```
$ composer global require brainsum/drupal-dev-tools:'^0.2.0' drupal-composer/drupal-security-advisories:'8.x-dev' drupal/examples:'1.x-dev' symfony/debug:'3.0.0' symfony/console:'2.8.27'
```
However, as it still not led to success, I'm quite doubted whether it's the proper way to do so...

**Comment by mhavelant** [comment]
This is not a global package, you have to add it to a project.

**Comment by balu-ertl** [comment]
Oh, that's okay. Was not obvious at first sight. Sure, after adding the repo declaration into project's own `composer.json` file and run `$ composer require brainsum/drupal-dev-tools:'^0.2.0' --dev` it's nicely installed, thanks.

**Comment by mhavelant** [comment]
Due to this, I opened #2, thanks!
