### ISSUE TITLE
Depracated warning with Php 7.3  - update grumphp

### ISSUE THREAD

**Issue by szatom** [brainsum/drupal-dev-tools#17]
PHP Deprecated:  strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /vendor/phpro/grumphp/src/Locator/ConfigurationFile.php on line 75

In grumphp it's already fixed, released in the v0.15.0 : https://github.com/phpro/grumphp/releases

We should depend on grumphp: ^0.15.0

**Comment by mhavelant** [comment]
Note, "matcher" has been removed from git commit/branch name tasks, manual update is required when importing the supplied `grumphp.yml`.

Before:
```yml
parameters:
    convention.git_commit_message_matchers: ['/^([A-Z]+-[\d]+ )+\| [A-Za-z\d\s\.]+([^.])+\.{1}$/s']
```

After:
```yml
parameters:
    convention.git_commit_message_whitelist: ['/^([A-Z]+-[\d]+ )+\| [A-Za-z\d\s\.]+([^.])+\.{1}$/s']
```
