### ISSUE TITLE
[Support request] "The option show_warnings does not exist"

### ISSUE THREAD

**Issue by balu-ertl** [brainsum/drupal-dev-tools#3]
After installation with Composer within a project (EL) I wanted to test how the checks run by trying to commit with an obviously fault message:
`$ git commit -m "DAM-00 - Ez most nem lenne szabad beengednie"`
However I stumbled upon into an issue when checking process arrives to `Phpcs` (occuring both in- and outside of the Docker container):
```
wodby@php.container:/var/www/html $ php ./vendor/bin/grumphp git:pre-commit
GrumPHP detected a pre-commit command.
GrumPHP is sniffing your code!
Running task 1/3: Composer... ✔
Running task 2/3: Phpcs...
In OptionsResolver.php line 747:
```
```
The option "show_warnings" does not exist. Defined options are: "encoding", "error_severity",
"ignore_patterns", "report", "report_width", "severity", "sniffs", "standard", "tab_width",
"triggered_by", "warning_severity", "whitelist_patterns".
```
After reading about how [GrumPHP utilizes](https://github.com/phpro/grumphp/blob/HEAD/doc/commands.md#git-hooks) Git hooks and how to [configure Code_Sniffer](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#hiding-warnings-by-default) to handle warnings, I managed to track back the source of the message which is probably sent by Symfony's [OptionsResolver](https://github.com/symfony/options-resolver/blob/master/OptionsResolver.php) component. 

But from this point I can't proceed further with figuring out how to make it properly working.

**Comment by mhavelant** [comment]
This package will not overwrite any existing grumphp.yml files. The old one has to be removed or renamed and this package has to be reinstalled. 
Note: Currently there should be around 8 checks configured, the copied CLI output shows 3.
Note2: #2

**Comment by balu-ertl** [comment]
Thanks for pointing to the right direction. Indeed, now it works. Steps how I managed to install:

1. An "_orig" postfix appended to the filename of the original (from EL project's master branch) `grumphp.yml` file (not deleted, kept there).
1. `wodby@php.container:/var/www/html $ composer require brainsum/drupal-dev-tools:'0.2.0' --dev`
1. I expected a new `grumphp.yml` to automatically appear beside the original one, but by some reason it did not happen. So I manually downloaded the [grumphp.dist.yml](https://github.com/brainsum/drupal-dev-tools/blob/b3b7038e4ea9754944c6f34493a2f83c91ace978/grumphp.dist.yml) from the repo and placed it there.
1. Now the checks run properly:
```wodby@php.container:/var/www/html $ git commit -m "DAM-00 - Ezt most nem lenne szabad beengednie"
GrumPHP detected a pre-commit command.
GrumPHP is sniffing your code!
Running task 1/8: Composer... ✔
Running task 2/8: BranchName... ✔
Running task 3/8: Phpcs... ✔
Running task 4/8: PhpLint... ✔
Running task 5/8: PhpParser... ✔
Running task 6/8: PhpVersion... ✔
Running task 7/8: SecurityChecker... ✔
Running task 8/8: YamlLint... ✔
GrumPHP detected a commit-msg command.
GrumPHP is sniffing your code!
Running task 1/1: CommitMessage... ✘```
